server:
  # 服务端口号
  port: 7777
spring:
  # 应用名称
  application:
    name: DEMO
  # jackson时间配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 上传文件配置
  servlet:
    multipart:
      # 单个最大文件大小
      max-file-size: 30MB
      # 总体文件最大请求大小
      max-request-size: 100MB
  # 数据库配置(p6spy)
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/blog?userUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/xml/*.xml